apiVersion: v1
kind: Pod
metadata:
    name: postgre-pod
    labels:
        names: postgres-pod
        app: demo-voting-app       
spec:
    containers:
        - name: postgres
          image: postgres:9.4
          ports:
          - containerPort: 5432
