apiVersion: v1
kind: Service
metadata:
    name: result-service
    labels:
        name: result-service
        app: demo-voting-app
spec:
    type: LoadBalancer
    ports:
        - targetPort: 80
          port: 80
    selector:
        name: result-app-pod
        paid: demo-voting-app
