apiVersion: v1
kind: Pod
metadata:
    name: result-app-pod
    labels:
        names: result-app-pod
        app: demo-result-app       
spec:
    containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
          - containerPort: 80
