apiVersion: v1
kind: Pod
metadata:
    name: worker-app-pod
    labels:
        names: worker-app-pod
        app: demo-worker-app       
spec:
    containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
